<?php
/**
 * Created by PhpStorm.
 * User: kot
 * Date: 09.12.16
 * Time: 18:58
 */

namespace backend\controllers;
use common\models\User;
use yii\web\Controller;
use Yii;

class AdminController  extends Controller
{
    public function beforeAction($action)
    {
        $isAllow = false;

        if (!Yii::$app->user->isGuest) {
            $user = User::findOne(Yii::$app->user->id);
            if ($user && $user->role == 'Administrator') {
                $isAllow = true;
            }
        }

        if (!$isAllow)
            $this->redirect('/error404');
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}