<?php
/**
 * Created by PhpStorm.
 * User: kot
 * Date: 09.12.16
 * Time: 19:18
 */

namespace frontend\modules\manager\controllers;
use yii\web\Controller;
use Yii;
use common\models\User;

class ManagerController  extends Controller
{

    protected $isModalLayout = false;

    public function beforeAction($action)
    {
        $isAllow = false;

        $layout = Yii::$app->request->get('layout', false);
        $this->isModalLayout = ($layout == 'modal');
        if ($this->isModalLayout) {
            $this->layout = 'modal';
        }

        if (!Yii::$app->user->isGuest) {
            $user = User::findOne(Yii::$app->user->id);
            if ($user && ($user->role == 'Administrator' || $user->role == 'Manager')) {
                $isAllow = true;
            }
        }

        if (!$isAllow)
            $this->redirect('/error404');
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}